# Generated by Django 4.2.30 on 2026-09-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('communications', '0002_alter_announcement_school_alter_notice_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Optional school tenant; null for platform-wide announcements.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='schools.school'),
        ),
    ]
