# Generated by Django 4.2.30 on 2026-09-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='school',
            field=models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='guardianstudent',
            name='school',
            field=models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='school',
            field=models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school'),
        ),
    ]
