# Generated by Django 4.2.30 on 2026-10-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_guardian_archived_at_guardian_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='genotype',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC'), ('SC', 'SC')], max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='lga',
            field=models.CharField(blank=True, max_length=100, verbose_name='Local Government Area'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Allergies, chronic conditions or medications staff should know about.'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='Nigerian', max_length=60),
        ),
        migrations.AddField(
            model_name='student',
            name='nin',
            field=models.CharField(blank=True, max_length=11, verbose_name='National Identification Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('christianity', 'Christianity'), ('islam', 'Islam'), ('traditional', 'Traditional'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
