# Generated by Django 4.2.30 on 2026-09-09 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_alter_feecategory_school_alter_feestructure_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('salaries', 'Salaries & Wages'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance & Repairs'), ('supplies', 'Supplies & Consumables'), ('transport', 'Transport'), ('catering', 'Catering'), ('rent', 'Rent / Lease'), ('insurance', 'Insurance'), ('events', 'Events & Activities'), ('other', 'Other')], default='other', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='finance/receipts/')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='schools.term')),
            ],
            options={
                'verbose_name': 'Expense',
                'ordering': ['-expense_date'],
            },
        ),
    ]
