# Generated by Django 4.2.30 on 2026-09-09 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_adoption_features_p1'),
        ('finance', '0003_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "Full Payment", "2-Instalment"', max_length=100)),
                ('number_of_instalments', models.PositiveIntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='finance.feestructure')),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['number_of_instalments'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='current_installment_sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('cheque', 'Cheque'), ('ussd', 'USSD'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=60, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='finance/receipts/')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finance.payment')),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.installmentplan'),
        ),
        migrations.CreateModel(
            name='InstallmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=60)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='finance.installmentplan')),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('plan', 'sequence')},
            },
        ),
    ]
