# Generated by Django 4.2.30 on 2026-09-09 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_guardian_school_alter_guardianstudent_school_and_more'),
        ('academics', '0002_alter_class_school_alter_classsubject_school_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('previous_class', models.CharField(blank=True, max_length=100)),
                ('additional_info', models.TextField(blank=True)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_relationship', models.CharField(default='guardian', max_length=50)),
                ('guardian_phone', models.CharField(max_length=30)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_address', models.TextField(blank=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='admissions/photos/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='admissions/docs/')),
                ('previous_result', models.FileField(blank=True, null=True, upload_to='admissions/docs/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='admissions/docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('generated_admission_number', models.CharField(blank=True, max_length=50)),
                ('applying_for_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='academics.class')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='schools.academicsession')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='students.student')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(default='ADM', max_length=20)),
                ('include_year', models.BooleanField(default=True)),
                ('year_format', models.CharField(default='%Y', help_text='strftime format for year part, e.g. %Y or %y', max_length=10)),
                ('separator', models.CharField(default='/', max_length=5)),
                ('sequence_digits', models.PositiveSmallIntegerField(default=4)),
                ('current_sequence', models.PositiveIntegerField(default=0)),
                ('custom_format', models.CharField(blank=True, help_text='Optional override. Use {prefix}, {year}, {seq} placeholders. Leave blank to use standard prefix/year/seq format.', max_length=200)),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'verbose_name': 'Admission Config',
                'verbose_name_plural': 'Admission Configs',
                'unique_together': {('school',)},
            },
        ),
    ]
