# Generated by Django 4.2.30 on 2026-09-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='intake_channel',
            field=models.CharField(choices=[('web', 'Web Form'), ('whatsapp', 'WhatsApp'), ('email_link', 'Email Link'), ('admin', 'Admin')], default='web', max_length=20),
        ),
    ]
