# Generated by Django 4.2.30 on 2026-09-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutorial_completed',
            field=models.BooleanField(default=False, help_text='True once the user has completed or dismissed the onboarding tutorial.'),
        ),
    ]
