# Generated by Django 4.2.30 on 2026-09-09 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_adoption_features_p1'),
        ('accounts', '0002_user_tutorial_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='True for sandbox/demo guest accounts.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', help_text='Preferred channel for notifications and auth codes.', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='school_group',
            field=models.ForeignKey(blank=True, help_text='Group this user owns/belongs to (Group Owner role).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_users', to='schools.schoolgroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number in E.164 format, e.g. +2348012345678', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('group_owner', 'Group/Proprietor Owner'), ('school_admin', 'School Admin'), ('staff', 'Staff'), ('accountant', 'Accountant'), ('parent', 'Parent'), ('student', 'Student'), ('guest', 'Guest/Demo')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('login', 'Login OTP'), ('password_reset', 'Password Reset'), ('email_verify', 'Email Verification'), ('registration', 'Registration Link')], default='login', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
