# Generated by Django 4.2.30 on 2026-09-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adoption_features_p1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('group_owner', 'Group/Proprietor Owner'), ('school_admin', 'School Admin'), ('principal', 'Principal / Head'), ('vice_principal', 'Vice Principal'), ('admissions_officer', 'Admissions Officer'), ('teacher', 'Teacher'), ('form_teacher', 'Form Teacher'), ('exam_officer', 'Exam Officer'), ('hr_admin', 'HR / Staff Admin'), ('librarian', 'Librarian'), ('staff', 'Staff'), ('accountant', 'Accountant'), ('parent', 'Parent'), ('student', 'Student'), ('guest', 'Guest/Demo')], default='staff', max_length=20),
        ),
    ]
