# Generated by Django 4.2.30 on 2026-09-09 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_guardian_school_alter_guardianstudent_school_and_more'),
        ('academics', '0002_alter_class_school_alter_classsubject_school_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('homework', 'Homework'), ('classwork', 'Classwork'), ('project', 'Project'), ('essay', 'Essay'), ('test', 'Test')], default='homework', max_length=20)),
                ('due_date', models.DateField()),
                ('max_points', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/assignments/')),
                ('is_published', models.BooleanField(default=True)),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_assignments', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.term')),
            ],
            options={
                'verbose_name': 'Assignment',
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LiveLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('jitsi_room_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live Now'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_lessons', to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_lessons', to='academics.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Lesson',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='homework/submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late'), ('graded', 'Graded'), ('returned', 'Returned')], default='submitted', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student')),
            ],
            options={
                'verbose_name': 'Submission',
                'ordering': ['-submitted_at'],
                'unique_together': {('school', 'assignment', 'student')},
            },
        ),
    ]
