# Generated by Django 4.2.30 on 2026-09-09 22:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_class_school_alter_classsubject_school_and_more'),
        ('schools', '0001_initial'),
        ('students', '0002_alter_guardian_school_alter_guardianstudent_school_and_more'),
        ('gradebook', '0002_alter_assessment_school_alter_grade_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('ca1_weight', models.PositiveSmallIntegerField(default=20, help_text='Weight for Continuous Assessment 1 (e.g. 20 = 20%)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('ca2_weight', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)])),
                ('exam_weight', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(100)])),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'verbose_name': 'Grading Scheme',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='reportcard',
            name='class_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='next_term_begins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='principal_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.class'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='subjects_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('exam', 'Exam'), ('ca1', 'Continuous Assessment 1'), ('ca2', 'Continuous Assessment 2'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('project', 'Project'), ('mid_term', 'Mid Term')], default='exam', max_length=20),
        ),
        migrations.CreateModel(
            name='ResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ca1_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ca2_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('grade_remark', models.CharField(blank=True, max_length=50)),
                ('grade_points', models.PositiveSmallIntegerField(default=0)),
                ('subject_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='gradebook.gradingscheme')),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='schools.term')),
            ],
            options={
                'verbose_name': 'Result Summary',
                'verbose_name_plural': 'Result Summaries',
                'ordering': ['subject__name'],
                'unique_together': {('school', 'student', 'term', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='GradeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. A1, B2, F9', max_length=10)),
                ('remark', models.CharField(help_text='e.g. Excellent, Pass', max_length=50)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points', models.PositiveSmallIntegerField(default=0, help_text='Grade point (for GPA computation), e.g. A1=5')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='gradebook.gradingscheme')),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'verbose_name': 'Grade Boundary',
                'ordering': ['-min_score'],
                'unique_together': {('school', 'scheme', 'label')},
            },
        ),
    ]
