# Generated by Django 4.2.30 on 2026-09-09 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_adoption_features_p1'),
        ('students', '0002_alter_guardian_school_alter_guardianstudent_school_and_more'),
        ('gradebook', '0003_gradingscheme_reportcard_class_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtRiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag_type', models.CharField(choices=[('grade_decline', 'Consecutive Grade Decline'), ('low_attendance', 'Attendance Below Threshold'), ('multiple', 'Multiple Risk Factors')], default='grade_decline', max_length=20)),
                ('reason', models.TextField(help_text='Human-readable explanation of the risk signal.')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('notified_teacher', models.BooleanField(default=False)),
                ('notified_parent', models.BooleanField(default=False)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='schools.term')),
            ],
            options={
                'verbose_name': 'At-Risk Flag',
                'ordering': ['-flagged_at'],
                'unique_together': {('school', 'student', 'term', 'flag_type')},
            },
        ),
    ]
