# Generated by Django 4.2.30 on 2026-10-02 06:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_requested_modules'),
        ('gradebook', '0005_assessment_archived_at_assessment_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='class_average',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Average score across the whole class — parents compare against the pupil's own average.", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='days_open',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='days_present',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TraitRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('affective', 'Affective (Behaviour)'), ('psychomotor', 'Psychomotor (Skills)')], max_length=15)),
                ('trait', models.CharField(max_length=60)),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 scale (1 = poor … 5 = excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_ratings', to='gradebook.reportcard')),
                ('school', models.ForeignKey(help_text='School tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['category', 'trait'],
                'unique_together': {('school', 'report_card', 'category', 'trait')},
            },
        ),
    ]
