# Generated by Django 4.2.30 on 2026-09-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_adoption_features_p1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('student_count_range', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('contacted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
