# Generated by Django 4.2.30 on 2026-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_demolead'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='school',
            name='report_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='school',
            name='report_template',
            field=models.FileField(blank=True, null=True, upload_to='schools/report_templates/'),
        ),
    ]
