# Generated by Django 4.2.30 on 2026-09-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_academicsession_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
    ]
