# Generated by Django 4.2.30 on 2026-09-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='requested_modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
